import Link from "next/link";
import {
  ArrowRight,
  BookOpen,
  ExternalLink,
  KeyRound,
  PackageCheck,
  ShieldCheck,
  Webhook,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { createPageMetadata } from "@/lib/seo";
import { getSwaggerDocsUrl } from "@/lib/swagger-docs-url";

const DOCS_DESCRIPTION =
  "Integrate with the Waybridge logistics API: authentication, shipment tracking, webhooks, delivery history, and the complete endpoint reference.";

export const dynamic = "force-dynamic";

export const metadata = createPageMetadata({
  title: "API documentation",
  description: DOCS_DESCRIPTION,
  path: "/docs",
});

type HttpMethod = "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
type AccessLevel = "Public" | "Refresh cookie" | "Bearer" | "Admin";

type Endpoint = {
  method: HttpMethod;
  path: string;
  access: AccessLevel;
  description: string;
};

type EndpointGroup = {
  id: string;
  title: string;
  description: string;
  endpoints: Endpoint[];
};

const ENDPOINT_GROUPS: EndpointGroup[] = [
  {
    id: "health",
    title: "Health",
    description: "Public checks for confirming that the API process is responding.",
    endpoints: [
      {
        method: "GET",
        path: "/",
        access: "Public",
        description: "Returns a lightweight response when the API is running.",
      },
      {
        method: "GET",
        path: "/health",
        access: "Public",
        description: "Returns the API health status.",
      },
      {
        method: "GET",
        path: "/api/health",
        access: "Public",
        description: "Compatibility alias for the health check.",
      },
    ],
  },
  {
    id: "authentication",
    title: "Authentication",
    description:
      "Registration and sign-in issue short-lived access tokens and establish a server-managed refresh session.",
    endpoints: [
      {
        method: "POST",
        path: "/api/auth/register",
        access: "Public",
        description:
          "Creates a customer account from name, email, and password. Registration always assigns the customer role, returns data.token, and sets an HttpOnly refresh cookie.",
      },
      {
        method: "POST",
        path: "/api/auth/login",
        access: "Public",
        description:
          "Signs in with email and password, returning data.accessToken and its data.token alias, and setting an HttpOnly refresh cookie.",
      },
      {
        method: "POST",
        path: "/api/auth/refresh",
        access: "Refresh cookie",
        description:
          "Rotates the refresh session cookie and issues a new access token. Send the cookie with credentials; do not put a refresh token in JSON.",
      },
      {
        method: "POST",
        path: "/api/auth/logout",
        access: "Public",
        description:
          "Revokes the current refresh session when present and clears the browser cookie.",
      },
      {
        method: "POST",
        path: "/api/auth/change-password",
        access: "Bearer",
        description:
          "Changes the current user's password using currentPassword and newPassword. A successful change revokes all refresh sessions and requires signing in again.",
      },
      {
        method: "GET",
        path: "/api/auth/me",
        access: "Bearer",
        description: "Returns the authenticated user's public profile.",
      },
    ],
  },
  {
    id: "shipments",
    title: "Shipments",
    description:
      "Create shipments, manage their ownership, and advance them through the supported delivery lifecycle.",
    endpoints: [
      {
        method: "GET",
        path: "/api/shipments",
        access: "Bearer",
        description:
          "Lists shipments visible to the caller. Customers see their assigned shipments; admins see all. Supports page, limit, search, and status filters.",
      },
      {
        method: "POST",
        path: "/api/shipments",
        access: "Bearer",
        description:
          "Creates a shipment from origin, destination, and amount. Admins also supply customer and may supply customerId; customer callers must omit customerId. Tracking numbers are generated by the API.",
      },
      {
        method: "GET",
        path: "/api/shipments/{id}",
        access: "Bearer",
        description:
          "Returns shipment details. Customers can read only shipments assigned to them; admins can read any shipment.",
      },
      {
        method: "PATCH",
        path: "/api/shipments/{id}/customer",
        access: "Admin",
        description:
          "Assigns the shipment to an existing customer using a customerId request field.",
      },
      {
        method: "PATCH",
        path: "/api/shipments/{id}/status",
        access: "Admin",
        description:
          "Advances the shipment using a status and optional note. Valid transitions append history, emit an event, and queue matching webhooks.",
      },
    ],
  },
  {
    id: "tracking",
    title: "Tracking",
    description:
      "Public tracking is intended for customers checking progress without creating an account.",
    endpoints: [
      {
        method: "GET",
        path: "/api/tracking/{trackingNumber}",
        access: "Public",
        description:
          "Returns the shipment status and timeline. Tracking numbers use the TRK- plus five digits format; limited to 60 requests per IP per 15 minutes.",
      },
    ],
  },
  {
    id: "events",
    title: "Events",
    description:
      "Admin event history for shipment changes and webhook test events.",
    endpoints: [
      {
        method: "GET",
        path: "/api/events",
        access: "Admin",
        description:
          "Lists events newest-first. Supports page, limit, type, and public event ID search.",
      },
      {
        method: "GET",
        path: "/api/events/{id}",
        access: "Admin",
        description:
          "Returns an event by MongoDB ObjectId or public ID such as evt_123456.",
      },
    ],
  },
  {
    id: "webhooks",
    title: "Webhooks",
    description:
      "Subscribe HTTPS endpoints to shipment events. Customers manage their own hooks; admins can inspect all hooks.",
    endpoints: [
      {
        method: "GET",
        path: "/api/webhooks",
        access: "Bearer",
        description:
          "Lists visible webhooks with masked secrets. Supports page, limit, search, active/isActive, and event filters.",
      },
      {
        method: "POST",
        path: "/api/webhooks",
        access: "Bearer",
        description:
          "Creates a webhook from name, URL, and one or more event types, with optional active state. The full signing secret is returned only in this response.",
      },
      {
        method: "GET",
        path: "/api/webhooks/{id}",
        access: "Bearer",
        description:
          "Returns a webhook visible to the caller. The signing secret is masked.",
      },
      {
        method: "PATCH",
        path: "/api/webhooks/{id}",
        access: "Bearer",
        description:
          "Partially updates a visible webhook using name, url, events, or active/isActive. Set regenerateSecret to true to rotate its secret; the replacement is returned once.",
      },
      {
        method: "PUT",
        path: "/api/webhooks/{id}",
        access: "Bearer",
        description:
          "Compatibility alias with the same partial-update behavior as PATCH.",
      },
      {
        method: "DELETE",
        path: "/api/webhooks/{id}",
        access: "Bearer",
        description:
          "Deletes a webhook owned by the caller; admins can delete any webhook.",
      },
      {
        method: "GET",
        path: "/api/webhooks/{id}/deliveries",
        access: "Bearer",
        description:
          "Lists delivery summaries for a webhook visible to the caller.",
      },
      {
        method: "POST",
        path: "/api/webhooks/{id}/test",
        access: "Bearer",
        description:
          "Queues a one-off webhook.test delivery. The response confirms the work was queued, not that the receiver accepted it.",
      },
    ],
  },
  {
    id: "deliveries",
    title: "Deliveries",
    description:
      "Inspect webhook delivery outcomes and attempt history, or queue another attempt.",
    endpoints: [
      {
        method: "GET",
        path: "/api/deliveries",
        access: "Bearer",
        description:
          "Lists delivery summaries visible to the caller. Supports page, limit, status, webhookId, and eventId filters.",
      },
      {
        method: "GET",
        path: "/api/deliveries/{id}",
        access: "Bearer",
        description:
          "Returns a delivery summary and ordered attempt history. Accepts a summary ID or historical attempt ID.",
      },
      {
        method: "POST",
        path: "/api/deliveries/{id}/resend",
        access: "Bearer",
        description:
          "Queues another attempt for a visible delivery. The response does not wait for the receiver.",
      },
      {
        method: "POST",
        path: "/api/deliveries/{id}/retry",
        access: "Bearer",
        description:
          "Compatibility alias for POST /api/deliveries/{id}/resend.",
      },
    ],
  },
  {
    id: "demo-receiver",
    title: "Demo Receiver",
    description:
      "A test webhook destination with an optional success/failure profile. These routes are not mounted in production unless ENABLE_DEMO_RECEIVER=true.",
    endpoints: [
      {
        method: "POST",
        path: "/api/demo-receiver",
        access: "Public",
        description:
          "Records an incoming JSON webhook and verifies an optional signature. Default response is 201; limited to 1,200 POST requests per IP per 15 minutes.",
      },
      {
        method: "GET",
        path: "/api/demo-receiver",
        access: "Admin",
        description:
          "Lists recorded requests with page, limit, signatureValid, and event filters. In-memory history retains at most 100 requests.",
      },
      {
        method: "DELETE",
        path: "/api/demo-receiver",
        access: "Admin",
        description: "Clears the recorded request history.",
      },
      {
        method: "POST",
        path: "/api/demo-receiver/fail",
        access: "Public",
        description:
          "Uses the configured failure profile; the default is HTTP 500, but admins can configure a 4xx/5xx status and response body.",
      },
      {
        method: "GET",
        path: "/api/demo-receiver/config",
        access: "Admin",
        description:
          "Returns the current success and failure response profiles. Profiles reset when the backend restarts.",
      },
      {
        method: "PATCH",
        path: "/api/demo-receiver/config",
        access: "Admin",
        description:
          "Updates a success and/or failure statusCode and body. Success codes must be 200-299; failure codes must be 400-599.",
      },
      {
        method: "DELETE",
        path: "/api/demo-receiver/config",
        access: "Admin",
        description: "Restores the default response profiles.",
      },
    ],
  },
];

const SECTION_LINKS = [
  { id: "quick-start", label: "Quick start" },
  { id: "authentication-guide", label: "Authentication" },
  { id: "conventions", label: "Conventions" },
  { id: "shipment-lifecycle", label: "Shipment lifecycle" },
  { id: "webhook-delivery-guide", label: "Webhook delivery" },
  { id: "api-reference", label: "All endpoints" },
  ...ENDPOINT_GROUPS.map(({ id, title }) => ({
    id,
    label: id === "authentication" ? "Auth routes" : title,
  })),
];

const METHOD_STYLES: Record<HttpMethod, string> = {
  GET: "bg-sky-500/10 text-sky-700 dark:text-sky-300",
  POST: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300",
  PATCH: "bg-amber-500/10 text-amber-700 dark:text-amber-300",
  PUT: "bg-violet-500/10 text-violet-700 dark:text-violet-300",
  DELETE: "bg-rose-500/10 text-rose-700 dark:text-rose-300",
};

const ACCESS_LABELS: Record<AccessLevel, string> = {
  Public: "Public",
  "Refresh cookie": "Refresh cookie",
  Bearer: "Bearer token",
  Admin: "Admin only",
};

function EndpointSection({ group }: { group: EndpointGroup }) {
  return (
    <section id={group.id} className="scroll-mt-24 space-y-4">
      <div className="space-y-2">
        <div className="flex flex-wrap items-center gap-3">
          <h2 className="text-2xl font-semibold tracking-tight">{group.title}</h2>
          <span className="rounded-full bg-muted px-2.5 py-1 text-xs text-muted-foreground">
            {group.endpoints.length} operations
          </span>
        </div>
        <p className="max-w-3xl text-sm leading-6 text-muted-foreground">
          {group.description}
        </p>
      </div>

      <div className="overflow-hidden rounded-xl border">
        <div className="hidden grid-cols-[5rem_minmax(14rem,1.1fr)_minmax(18rem,1.4fr)] gap-4 bg-muted/60 px-4 py-3 text-xs font-medium uppercase tracking-wide text-muted-foreground md:grid">
          <span>Method</span>
          <span>Path</span>
          <span>Access and behavior</span>
        </div>
        <div className="divide-y">
          {group.endpoints.map((endpoint) => (
            <article
              key={`${endpoint.method}-${endpoint.path}`}
              className="grid gap-2 p-4 md:grid-cols-[5rem_minmax(14rem,1.1fr)_minmax(18rem,1.4fr)] md:items-start md:gap-4"
            >
              <span
                className={`inline-flex w-fit min-w-16 justify-center rounded-md px-2 py-1 font-mono text-xs font-semibold ${METHOD_STYLES[endpoint.method]}`}
              >
                {endpoint.method}
              </span>
              <code className="break-all font-mono text-sm text-foreground">
                {endpoint.path}
              </code>
              <div className="space-y-1">
                <p className="text-xs font-semibold text-foreground">
                  {ACCESS_LABELS[endpoint.access]}
                </p>
                <p className="text-sm leading-6 text-muted-foreground">
                  {endpoint.description}
                </p>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}

export default function DocsPage() {
  const swaggerDocsUrl = getSwaggerDocsUrl();
  const operationCount = ENDPOINT_GROUPS.reduce(
    (total, group) => total + group.endpoints.length,
    0,
  );

  return (
    <div className="mx-auto flex w-full max-w-6xl flex-col gap-14 px-4 py-12 sm:px-6 sm:py-16">
      <header className="space-y-8">
        <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
          <div className="max-w-3xl space-y-4">
            <p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">
              Waybridge API | Version 1.0.0
            </p>
            <h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">
              Build with the Waybridge API
            </h1>
            <p className="max-w-2xl text-lg leading-8 text-muted-foreground">
              Connect shipment operations to your own systems. This guide covers
              the API conventions, authentication, events, and every documented
              endpoint.
            </p>
          </div>
          <div className="flex flex-col items-start gap-2">
            <Button asChild size="lg">
              <a
                href={swaggerDocsUrl}
                target="_blank"
                rel="noopener noreferrer"
                aria-label="Open the live Swagger API reference in a new tab"
              >
                Open live Swagger
                <ExternalLink aria-hidden="true" />
              </a>
            </Button>
            <span className="text-xs text-muted-foreground">
              Interactive reference for the configured backend
            </span>
          </div>
        </div>

        <div className="grid gap-3 rounded-2xl border bg-muted/30 p-4 sm:grid-cols-3 sm:p-5">
          <div className="flex items-start gap-3">
            <BookOpen className="mt-0.5 size-5 shrink-0 text-primary" aria-hidden="true" />
            <div>
              <p className="font-medium">API base path</p>
              <p className="mt-1 text-sm text-muted-foreground">
                Routes use <code className="font-mono">/api</code> on the backend origin.
              </p>
            </div>
          </div>
          <div className="flex items-start gap-3">
            <KeyRound className="mt-0.5 size-5 shrink-0 text-primary" aria-hidden="true" />
            <div>
              <p className="font-medium">Authentication</p>
              <p className="mt-1 text-sm text-muted-foreground">
                Short-lived bearer access tokens with HttpOnly refresh sessions.
              </p>
            </div>
          </div>
          <div className="flex items-start gap-3">
            <Webhook className="mt-0.5 size-5 shrink-0 text-primary" aria-hidden="true" />
            <div>
              <p className="font-medium">Webhook events</p>
              <p className="mt-1 text-sm text-muted-foreground">
                Signed deliveries, observable attempts, and explicit retries.
              </p>
            </div>
          </div>
        </div>
      </header>

      <nav aria-label="On this page" className="space-y-3">
        <p className="text-sm font-semibold">On this page</p>
        <div className="flex flex-wrap gap-2">
          {SECTION_LINKS.map(({ id, label }) => (
            <a
              key={id}
              href={`#${id}`}
              className="rounded-full border px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            >
              {label}
            </a>
          ))}
        </div>
      </nav>

      <section id="quick-start" className="scroll-mt-24 space-y-5">
        <div className="max-w-3xl space-y-2">
          <h2 className="text-2xl font-semibold tracking-tight">Quick start</h2>
          <p className="leading-7 text-muted-foreground">
            Set your backend origin, then append the route path shown below.
            <code className="mx-1 rounded bg-muted px-1.5 py-0.5 font-mono text-sm text-foreground">
              BACKEND_API_URL
            </code>
            is configured as the API base ending in <code className="font-mono">/api</code>;
            the route examples already include that prefix.
          </p>
        </div>

        <div className="grid gap-4 lg:grid-cols-3">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <span className="grid size-7 place-items-center rounded-full bg-primary/10 text-sm text-primary">
                  1
                </span>
                Choose the backend origin
              </CardTitle>
              <CardDescription>
                For example, localhost:5000 or your deployed backend host.
              </CardDescription>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <span className="grid size-7 place-items-center rounded-full bg-primary/10 text-sm text-primary">
                  2
                </span>
                Use JSON requests
              </CardTitle>
              <CardDescription>
                Send <code className="font-mono">Content-Type: application/json</code> for
                JSON request bodies. The maximum body size is 1 MiB.
              </CardDescription>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <span className="grid size-7 place-items-center rounded-full bg-primary/10 text-sm text-primary">
                  3
                </span>
                Authenticate private calls
              </CardTitle>
              <CardDescription>
                Add the access token as a bearer token. Public tracking does not
                need an account.
              </CardDescription>
            </CardHeader>
          </Card>
        </div>

        <div className="grid gap-4 lg:grid-cols-2">
          <div className="space-y-3">
            <h3 className="font-semibold">Public tracking request</h3>
            <pre className="overflow-x-auto rounded-xl border bg-muted/30 p-4 text-xs leading-6 sm:text-sm">
              <code>{`curl https://<backend-host>/api/tracking/TRK-12345`}</code>
            </pre>
          </div>
          <div className="space-y-3">
            <h3 className="font-semibold">Create a shipment</h3>
            <pre className="overflow-x-auto rounded-xl border bg-muted/30 p-4 text-xs leading-6 sm:text-sm">
              <code>{`curl --request POST https://<backend-host>/api/shipments \\
  -H "Authorization: Bearer <access-token>" \\
  -H "Content-Type: application/json" \\
  --data '{"origin":"London","destination":"Paris","amount":42.5}'`}</code>
            </pre>
          </div>
        </div>
      </section>

      <section id="authentication-guide" className="scroll-mt-24 space-y-5">
        <div className="max-w-3xl space-y-2">
          <h2 className="text-2xl font-semibold tracking-tight">
            Authentication and access
          </h2>
          <p className="leading-7 text-muted-foreground">
            Registration and login issue a 15-minute access token. Send it in
            the <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-sm text-foreground">Authorization: Bearer</code>{" "}
            header for protected operations.
          </p>
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <KeyRound className="size-5 text-primary" aria-hidden="true" />
                Access and refresh
              </CardTitle>
              <CardDescription>
                Keep access tokens short-lived and let the backend manage refresh
                sessions in an HttpOnly cookie.
              </CardDescription>
            </CardHeader>
            <CardContent className="text-sm leading-6 text-muted-foreground">
              Registration returns the access token as <code className="font-mono">data.token</code>.
              Login and refresh return <code className="font-mono">data.accessToken</code> and a
              compatible <code className="font-mono">data.token</code> alias. The refresh token
              itself is never returned in JSON. Browser clients must send
              credentialed requests to the configured CORS origin when refreshing.
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <ShieldCheck className="size-5 text-primary" aria-hidden="true" />
                Roles and ownership
              </CardTitle>
              <CardDescription>
                Public registration always creates a customer account.
              </CardDescription>
            </CardHeader>
            <CardContent className="text-sm leading-6 text-muted-foreground">
              Customers can access their own shipments, webhooks, and delivery
              summaries. Admin-only operations are marked in the endpoint
              reference. A resource outside a customer&apos;s ownership may be
              reported as not found.
            </CardContent>
          </Card>
        </div>
        <p className="rounded-xl border-l-4 border-primary bg-muted/30 px-4 py-3 text-sm leading-6 text-muted-foreground">
          Refresh cookies are scoped to <code className="font-mono text-foreground">/api/auth</code>{" "}
          and last 30 days. Outside production the cookie is named{" "}
          <code className="font-mono text-foreground">refreshToken</code>; production HTTPS uses{" "}
          <code className="font-mono text-foreground">__Secure-refreshToken</code>. The default
          SameSite policy is Strict.
        </p>
      </section>

      <section id="conventions" className="scroll-mt-24 space-y-5">
        <div className="max-w-3xl space-y-2">
          <h2 className="text-2xl font-semibold tracking-tight">
            Responses, pagination, and limits
          </h2>
          <p className="leading-7 text-muted-foreground">
            Successful responses use a consistent envelope. List operations
            return page metadata and resource arrays under <code className="font-mono">data</code>.
          </p>
        </div>

        <div className="grid gap-4 lg:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Response shape</CardTitle>
              <CardDescription>Read the envelope before the resource data.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3 text-sm leading-6 text-muted-foreground">
              <pre className="overflow-x-auto rounded-lg bg-muted/50 p-3 font-mono text-xs leading-5 text-foreground">
                <code>{`{
  "success": true,
  "message": "Shipment retrieved",
  "data": { "...": "..." }
}`}</code>
              </pre>
              <p>
                Errors use <code className="font-mono">success: false</code>, a message, and{" "}
                <code className="font-mono">data: null</code>. Validation errors also include an{" "}
                <code className="font-mono">errors</code> array with field and message details.
              </p>
              <p>
                Paginated data includes <code className="font-mono">items</code>, a resource-named
                array alias, and <code className="font-mono">pagination</code> with page, limit,
                total, totalItems, and totalPages.
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Pagination defaults</CardTitle>
              <CardDescription>
                Pages are one-based. Limits vary by resource.
              </CardDescription>
            </CardHeader>
            <CardContent className="overflow-x-auto">
              <table className="w-full min-w-64 text-left text-sm">
                <caption className="sr-only">Default and maximum page limits by API resource</caption>
                <thead className="text-xs uppercase tracking-wide text-muted-foreground">
                  <tr>
                    <th className="pb-2 pr-4 font-medium">Resource</th>
                    <th className="pb-2 pr-4 font-medium">Default</th>
                    <th className="pb-2 font-medium">Maximum</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  <tr><th scope="row" className="py-2 pr-4 font-medium">Shipments</th><td>20</td><td>100</td></tr>
                  <tr><th scope="row" className="py-2 pr-4 font-medium">Webhooks</th><td>10</td><td>50</td></tr>
                  <tr><th scope="row" className="py-2 pr-4 font-medium">Events</th><td>20</td><td>100</td></tr>
                  <tr><th scope="row" className="py-2 pr-4 font-medium">Deliveries</th><td>10</td><td>100</td></tr>
                  <tr><th scope="row" className="py-2 pr-4 font-medium">Demo receiver</th><td>20</td><td>50</td></tr>
                </tbody>
              </table>
            </CardContent>
          </Card>
        </div>

        <div className="grid gap-3 sm:grid-cols-3">
          <div className="rounded-xl border p-4">
            <p className="font-semibold">Request size</p>
            <p className="mt-1 text-sm leading-6 text-muted-foreground">
              JSON request bodies are limited to 1 MiB. Larger bodies return 413.
            </p>
          </div>
          <div className="rounded-xl border p-4">
            <p className="font-semibold">Rate limits</p>
            <p className="mt-1 text-sm leading-6 text-muted-foreground">
              Authentication: 20 requests per IP per 15 minutes. Public tracking:
              60 per IP per 15 minutes.
            </p>
          </div>
          <div className="rounded-xl border p-4">
            <p className="font-semibold">HTTP errors</p>
            <p className="mt-1 text-sm leading-6 text-muted-foreground">
              Expect 400 for invalid input, 401 for missing/invalid auth, 403 for
              role restrictions, 404 for unavailable resources, 413 for oversized
              bodies, 429 when rate limited, and 500 for unexpected server errors.
            </p>
          </div>
        </div>
      </section>

      <section id="shipment-lifecycle" className="scroll-mt-24 space-y-5">
        <div className="max-w-3xl space-y-2">
          <h2 className="text-2xl font-semibold tracking-tight">
            Shipment lifecycle and event types
          </h2>
          <p className="leading-7 text-muted-foreground">
            Status updates are validated transitions. A successful change appends
            shipment history, creates the corresponding event, and queues
            matching webhook deliveries.
          </p>
        </div>
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <PackageCheck className="size-5 text-primary" aria-hidden="true" />
              Supported statuses
            </CardTitle>
            <CardDescription>
              Delivered and cancelled are terminal states.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex flex-wrap gap-2">
              {[
                "created",
                "picked_up",
                "in_transit",
                "arrived_at_hub",
                "out_for_delivery",
                "delivered",
                "delivery_failed",
                "cancelled",
              ].map((status) => (
                <code
                  key={status}
                  className="rounded-md bg-muted px-2.5 py-1.5 font-mono text-xs"
                >
                  {status}
                </code>
              ))}
            </div>
            <p className="text-sm leading-6 text-muted-foreground">
              Allowed transitions: created &rarr; picked_up or cancelled; picked_up
              &rarr; in_transit or cancelled; in_transit &rarr; arrived_at_hub or
              cancelled; arrived_at_hub &rarr; in_transit, out_for_delivery, or
              cancelled; out_for_delivery &rarr; delivered or delivery_failed; and
              delivery_failed &rarr; out_for_delivery or cancelled. Delivered and
              cancelled are terminal.
            </p>
            <p className="text-sm leading-6 text-muted-foreground">
              Webhook event types are <code className="font-mono">shipment.created</code>,{" "}
              <code className="font-mono">shipment.picked_up</code>,{" "}
              <code className="font-mono">shipment.in_transit</code>,{" "}
              <code className="font-mono">shipment.arrived_at_hub</code>,{" "}
              <code className="font-mono">shipment.out_for_delivery</code>,{" "}
              <code className="font-mono">shipment.delivered</code>,{" "}
              <code className="font-mono">shipment.delivery_failed</code>,{" "}
              <code className="font-mono">shipment.cancelled</code>, and{" "}
              <code className="font-mono">webhook.test</code>.
            </p>
          </CardContent>
        </Card>
      </section>

      <section id="webhook-delivery-guide" className="scroll-mt-24 space-y-5">
        <div className="max-w-3xl space-y-2">
          <h2 className="text-2xl font-semibold tracking-tight">
            Receiving signed webhooks
          </h2>
          <p className="leading-7 text-muted-foreground">
            Each delivery is a JSON POST containing an event envelope. Verify its
            signature against the exact raw request body before parsing or
            trusting the payload.
          </p>
        </div>

        <div className="grid gap-4 lg:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Payload and signature</CardTitle>
              <CardDescription>
                The signing secret is shown in full only when a webhook is
                created or its secret is regenerated.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-3 text-sm leading-6 text-muted-foreground">
              <pre className="overflow-x-auto rounded-lg bg-muted/50 p-3 font-mono text-xs leading-5 text-foreground">
                <code>{`{
  "id": "evt_123456",
  "type": "shipment.created",
  "createdAt": "2026-10-03T10:00:00.000Z",
  "data": { "...": "event-specific payload" }
}`}</code>
              </pre>
              <p>
                Verify <code className="font-mono">X-Webhook-Signature</code> as{" "}
                <code className="font-mono">sha256=&lt;hex HMAC-SHA256&gt;</code> over{" "}
                <code className="font-mono">&lt;X-Webhook-Timestamp&gt;.&lt;exact raw body&gt;</code>,
                using the webhook secret. Compare digests in constant time.
              </p>
              <p>
                The request also includes <code className="font-mono">X-Webhook-Timestamp</code>,{" "}
                <code className="font-mono">X-Webhook-Event</code>, and{" "}
                <code className="font-mono">X-Webhook-Delivery</code>. Timestamped
                receiver verification allows at most five minutes of clock skew.
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Retries and receiver requirements</CardTitle>
              <CardDescription>
                Delivery attempts run asynchronously after an event is emitted.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-3 text-sm leading-6 text-muted-foreground">
              <p>
                Any 2xx response succeeds. Automatic delivery makes at most three
                attempts with 2-second and 5-second retry delays; each request
                times out after 5 seconds. Captured receiver response text is
                limited to 1,000 characters.
              </p>
              <p>
                Webhook URLs must use HTTP or HTTPS and cannot include URL
                credentials. Production requires HTTPS and blocks private,
                loopback, link-local, and reserved IP addresses after DNS
                resolution. Exact localhost is permitted only in development
                when ALLOW_LOCALHOST_WEBHOOKS and ENABLE_DEMO_RECEIVER are enabled;
                other loopback aliases remain blocked. Configure responses to{" "}
                <code className="font-mono">{"POST /api/webhooks/{id}/test"}</code> and{" "}
                <code className="font-mono">{"POST /api/deliveries/{id}/resend"}</code>{" "}
                confirm that work was queued, not that delivery succeeded.
              </p>
            </CardContent>
          </Card>
        </div>
      </section>

      <section id="api-reference" className="scroll-mt-24 space-y-3">
        <div className="max-w-3xl space-y-2">
          <h2 className="text-3xl font-semibold tracking-tight">Endpoint reference</h2>
          <p className="leading-7 text-muted-foreground">
            {operationCount} operations across health, authentication, shipment
            management, tracking, event history, webhooks, deliveries, and the
            demo receiver. Request and response schemas are available in the live
            Swagger UI.
          </p>
        </div>
      </section>

      <div className="flex flex-col gap-10">
        {ENDPOINT_GROUPS.map((group) => (
          <EndpointSection key={group.id} group={group} />
        ))}
      </div>

      <section className="rounded-2xl border bg-primary/[0.04] p-6 sm:p-8">
        <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
          <div className="space-y-2">
            <h2 className="text-xl font-semibold">Explore the interactive contract</h2>
            <p className="max-w-2xl text-sm leading-6 text-muted-foreground">
              Use Swagger to inspect full request schemas, response examples,
              and try operations against the live backend.
            </p>
          </div>
          <div className="flex flex-wrap gap-3">
            <Button asChild>
              <a
                href={swaggerDocsUrl}
                target="_blank"
                rel="noopener noreferrer"
                aria-label="Open the live Swagger API reference in a new tab"
              >
                Live Swagger
                <ExternalLink aria-hidden="true" />
              </a>
            </Button>
            <Button asChild variant="outline">
              <Link href="/about">
                About Waybridge
                <ArrowRight aria-hidden="true" />
              </Link>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
}
